### PR TITLE
Frontend display map

### PR DESCRIPTION
**Pull request by MaHambach**
Adds the functunality to the frontend to add a worldmap and to display it.

### CODE REVIEW

**Review by MarcellNF — CHANGES_REQUESTED** [review]
See Slack

**Review by MaHambach — COMMENTED** [review]
test

**Review by MarcellNF — CHANGES_REQUESTED** [review]
First fix your 5 frontend issues ;-)

**Review by MarcellNF — APPROVED** [review]
LGTM!:)

**Pull request merged**
